name: Test loadforecasting_framework

on:
  push:  
    paths:
      - 'src/**/*.py'
  pull_request:  
    paths:
      - 'src/**/*.py'

jobs:
  test_the_framework:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: load_forecasting
        environment-file: envs/env_linux.yml
        auto-activate-base: false

    - name: Show Conda Info 
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Install the local package
      shell: bash -l {0}
      run: |
        pip install --no-deps -e src/loadforecasting_models/
        pip install --no-deps -e .

    - name: Run the unittests   
      shell: bash -l {0}
      run: |
        python tests/unittest test_data_preprocessor.py
    
    - name: Run training script    
      shell: bash -l {0}
      run: |
        python src/loadforecasting_framework/model_trainer.py --mode ci        
